title: Just Another Webpage
author: Janglepants
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Why is everything amazing and awesome these days?

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
