title: I have nothing to say
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm just playing around making a webpage, maybe one day I'll make that cool desktop.
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
